### PR TITLE
feat: house keeping, version bumping, doc fixes, doc improvements, v2 home data api

### PR DESCRIPTION
**Pull request by Lash-L**
Hoping docs will not fail to build now as well

### CODE REVIEW

**Review by humbertogontijo — APPROVED** [review]
Looks good

**Comment by Lash-L** [comment]
@humbertogontijo There is a depreciation for read the docs that is going to take place in January.
https://blog.readthedocs.com/security-update-on-incoming-webhooks/

I think you can fix it by just going here and hitting resync webhook:
https://readthedocs.org/dashboard/python-roborock/integrations/238448/

But I don't have webhook permissions for this project, so I can't do it and I think you need to.

**Comment by Lash-L** [comment]
This now includes v2 of home_data api @humbertogontijo

**Comment by humbertogontijo** [comment]
https://readthedocs.org/dashboard/python-roborock/integrations/238448/ gave me a 404

**Review by humbertogontijo — APPROVED** [review]
Approved.
Nice job on home data v2 btw

**Comment by Lash-L** [comment]
> Approved.
> 
> Nice job on home data v2 btw

Thanks!

**Comment by Lash-L** [comment]
> https://readthedocs.org/dashboard/python-roborock/integrations/238448/ gave me a 404

Just login then go to python Roborock then admin then integrations

**Comment by humbertogontijo** [comment]
Somehow I can't see admin button
image

**Comment by Lash-L** [comment]
Ah seems like I only had maintainer rights for the docs. I have sent an invite to you - I would have figured it would have just given you the rights because you are the code owner here

**Pull request merged**
