### PR TITLE
fix: hopefully finalize semantic release

### PR DESCRIPTION
**Pull request by Lash-L**
I think i may finally have it figured out.

So long as the GH_TOKEN has full permission, this should work.

### CODE REVIEW

**Comment by Lash-L** [comment]
@humbertogontijo

**Review by humbertogontijo — APPROVED** [review]

**Comment by Lash-L** [comment]
@humbertogontijo does the GH_TOKEN you made have full permissions? It is unable to push to the main branch as it is protected

**Comment by humbertogontijo** [comment]
Can you try it one more time?

**Comment by Lash-L** [comment]
Same problem

                    GitCommandError: Cmd('git') failed due to:                  
                    exit code(1)                                                
                      cmdline: git push                                         
                    https://github.com/humbertogontijo/python-                  
                    roborock main                                               
                      stderr: 'remote: error: GH006: Protected                  
                    branch update failed for refs/heads/main.                   
                    remote:                                                     
                    remote: - Changes must be made through a                    
                    pull request.                                               
                    To                                                          
                    https://github.com/humbertogontijo/python-                  
                    roborock                                                    
                     ! [remote rejected]     main -> main                       
                    (protected branch hook declined)                            
                    error: failed to push some refs to                          
                    'https://github.com/humbertogontijo/python                  
                    -roborock''

**Comment by humbertogontijo** [comment]
It has all permissions now. Maybe this just won't work with protected branches?
What about using the automatically generated secrets.GITHUB_TOKEN again?

**Comment by Lash-L** [comment]
My understanding is that GITHUB_TOKEN uses the permissions of the end user. Since I can't push to protected branches, it will fail. If you merge it in - it might work?

**Comment by Lash-L** [comment]
I believe you can add the github actions bot to the list of users allowed to push to protected branches? Not sure off the top of my head and away from my PC now

**Pull request merged**
