### PR TITLE
feat: add datetime parsing in cleanrecord

### PR DESCRIPTION
**Pull request by Lash-L**

### CODE REVIEW

**Review by humbertogontijo — APPROVED** [review]
LGTM

**Comment by Lash-L** [comment]
It auto dismissed the review because I fixed linting, do you mind re-approving?

**Comment by Lash-L** [comment]
Added one more change with a is_available bool.

**Comment by Lash-L** [comment]
Also exposed queue timeout so it can be manipulated. Some users were facing issues with timeouts and I figured this way I can increase/decrease the timeout as needed

**Comment by Lash-L** [comment]
@humbertogontijo When you get a chance can you approve this? I have 3/4 PRs that are going to require this merge

**Review by humbertogontijo — APPROVED** [review]
Approved

**Comment by Lash-L** [comment]
Preesh thank you

**Pull request merged**
