### PR TITLE
feat: adding status and consumable listeners

### PR DESCRIPTION
**Pull request by humbertogontijo**
The mqtt client have messages for some attribute changes that are instantly. I'm creating some use for it here

### CODE REVIEW

**Comment by humbertogontijo** [comment]
This also fixes https://github.com/humbertogontijo/homeassistant-roborock/issues/395

**Comment by Lash-L** [comment]
Sorry I missed this and I've been out of commission lately. Been rather busy.

As an aside, in the component, instead of using self.api.cache.get, we should use

```    def get_cache(self, attribute: CacheableAttribute) -> AttributeCache:
        try:
            result = self._api.cache.get(attribute)
        except RoborockException as err:
            raise HomeAssistantError(f"Error while getting {attribute.name}") from err
        return result
```

To allow for HomeAssistant to recover gracefully on a failed error

I plan to add it to the custom side once I get done with the core side unless you have a chance to first

**Comment by humbertogontijo** [comment]
> Sorry I missed this and I've been out of commission lately. Been rather busy.
> 
> As an aside, in the component, instead of using self.api.cache.get, we should use
> 
> ```
>         try:
>             result = self._api.cache.get(attribute)
>         except RoborockException as err:
>             raise HomeAssistantError(f"Error while getting {attribute.name}") from err
>         return result
> ```
> 
> To allow for HomeAssistant to recover gracefully on a failed error
> 
> I plan to add it to the custom side once I get done with the core side unless you have a chance to first

Actually there shouldn't be any issue on this get. Only when calling api.cache[attribute].async_value()

**Comment by Lash-L** [comment]
That is a good point. I started working on it not realizing at first that the get was just a dict get and then I didn't think about it. Good call.

**Pull request merged**
