### PR TITLE
feat: Add Zeo support and fix some A01 weirdness

### PR DESCRIPTION
**Pull request by Lash-L**

### CODE REVIEW

**Comment by Lash-L** [comment]
Some bad git history - but i will squash so it wont matter.

**Review by humbertogontijo — APPROVED** [review]
Looks good.
The A01_AES_DECIPHER was intentionally deleted I suppose

**Comment by Lash-L** [comment]
> Looks good. The A01_AES_DECIPHER was intentionally deleted I suppose

Yeah it was being hardcoded instead of the local key.

Can you give it one more approval, I just pushed some more code mappings

**Comment by Lash-L** [comment]
Accidentally left a tag in there that bumped it major - but oh well. 1.0.0 was kind of broken anyways for a01.

**Pull request merged**
