### PR TITLE
fix: add a warning for wrong type of clean area and add new dock

### PR DESCRIPTION
**Pull request by Lash-L**

### CODE REVIEW

**Review by humbertogontijo — APPROVED** [review]

**Comment by Lash-L** [comment]
@humbertogontijo You need to add 2FA to your pypi account, it will not allow pushing to pypi otherwise

https://github.com/humbertogontijo/python-roborock/actions/runs/11420333457/job/31775927391#step:5:211

400 User 'humbertogontijo' does not have two-factor authentication enabled. Please enable two-factor authentication before attempting to upload to PyPI. See https://pypi.org/help/#two-factor-authentication for more information.

**Comment by Lash-L** [comment]
@humbertogontijo  Let me know when you have a chance to do it and i will try to repush to pypi

**Comment by Lash-L** [comment]
Any chance you could reset us back to commit c334eb2193091dccd23db0d3ee4863e838733e30 

Alternatively, I can make a new PR. But it wont rebuild as long as they 2.6.1 commit exists. I deleted the release and the tag, but I don't have permissions to do a force push or anything to remove the 2.6.1 commit

**Comment by humbertogontijo** [comment]
Done. You can create a new PR

**Pull request merged**
