### PR TITLE
feat: add q revo/p10 support

### PR DESCRIPTION
**Pull request by Jezza34000**
- Adding class for FanSpeed
- Adding class for MopMode (only 2 for Q REVO) 
- Adding const
- Adding many status from Q REVO get_status (some are unknow) :
  1.     wash_status: ???
  2.     distance_off: ???
  3.     in_warmup: ???
  4.     dry_status: 1-> Air dryer running 0-> Not running
  5.     rdt: Remaing Dryer Time (Count down timer in second)
  6.     clean_percent: From 0 to 100 in percent
  7.     rss: ???
  8.     dss: ???
  9.     common_status: ???
  10.     corner_clean_mode: ???

### CODE REVIEW

**Review by Lash-L — DISMISSED** [review]
All looks good to me. Optional should cover our bases

**Comment by Lash-L** [comment]
Also does this really make any changes regarding q revo?

**Comment by Jezza34000** [comment]
Yes roborock.vacuum.a75 is Q REVO or P10 
I think P10 is the CN name, and Q REVO for rest of the world

**Comment by Jezza34000** [comment]
OK i change my PR. mop_mode/route is exaclty same as S8ProUltra.
Commitlint should be ok, and i Black my code.

**Comment by Jezza34000** [comment]
Maybe we need a more generical name for class `RoborockMopModeS8ProUltra(RoborockMopModeCode)`
Now it's used by S8ProUltra And Q Revo

**Comment by Lash-L** [comment]
Please run pre-commit not just black. Or manually fix the issues listed in the failed ci check

**Review by Lash-L — APPROVED** [review]

**Comment by Jezza34000** [comment]
Hello thank you. :+1: 
I enabled the pre-commit hook for the next commits

**Pull request merged**
