### PR TITLE
fix: container issue from api change and ci update

### PR DESCRIPTION
**Pull request by Lash-L**
This fixes a broken change from api issues.

I also switched it back to GH_TOKEN, I don't have a real fix yet, but could you please merge it in, since you have permissions it should work.

### CODE REVIEW

**Comment by Lash-L** [comment]
@humbertogontijo Can you approve + merge this one. I think if you merge it - everything should work correctly and I need to get this out

**Review by humbertogontijo — APPROVED** [review]
Lets try it

**Comment by Lash-L** [comment]
Either way @humbertogontijo do you want to merge in this one as well?

https://github.com/humbertogontijo/python-roborock/pull/253

**Comment by Lash-L** [comment]
@humbertogontijo What are your thoughts about moving python-roborock to a github org?

Allen(from HA core team) is going to be helping out now I believe, so perhaps making it so that as long as any org owner (you, myself, or allen) approves the PR, it can be merged? That way I could approve his PRs or you could approve his PRs? He could approve mine or you could approve mine? etc.

**Comment by Lash-L** [comment]
@humbertogontijo  ^ I saw you joined the org, if this is somehting you want to go through with you'll need to transfer the repo to the org. I marked you as owner

**Comment by Lash-L** [comment]
> @humbertogontijo  ^ I saw you joined the org, if this is somehting you want to go through with you'll need to transfer the repo to the org. I marked you as owner

@humbertogontijo gonna ping one more time on this as I know there has been a lot of activity so you could have missed it. If this isn't something you want to go through with just lmk

**Comment by humbertogontijo** [comment]
I don't know how I missed this so many times. Sorry
I moved the repo to the organization

**Comment by Lash-L** [comment]
@humbertogontijo No worries! There was a lot happening in the repo!

**Pull request merged**
