### PR TITLE
feat: add custom state for charging and will continue

### PR DESCRIPTION
**Pull request by Lash-L**
This way a user can tell if their vacuum is just charging or if it is charging and planning to continue cleaning

### CODE REVIEW

**Comment by humbertogontijo** [comment]
Shouldn't this be done on automations and not in the library itself?

**Comment by Lash-L** [comment]
My thought was that this is generic enough of information that it should always be available to the user rather than the user having to specify it in an automation- and I'm surprised it is not a base state to begin with. But I'm open to not doing it.

It is kind of weird though since it takes a class that previously only specified data from the api directly and makes it semi-manual.

I'm open to going either way - was curious on your thoughts

**Comment by humbertogontijo** [comment]
How it goes in the app?

**Comment by Lash-L** [comment]
> How it goes in the app?

iirc - it says the device is charging and then the bottom part says 'stop' and 'dock' like it typically does when you can cancel a clean

**Comment by humbertogontijo** [comment]
I think it will be better not create sub statuses. Using in_cleaning as an entity might be the way to go

**Pull request closed without merging**
