### PR TITLE
fix: semantic release not updating changelong

### PR DESCRIPTION
**Pull request by Lash-L**
Per recommendation here: 

https://github.com/python-semantic-release/python-semantic-release/issues/575#issuecomment-1500904789

### CODE REVIEW

**Comment by humbertogontijo** [comment]
Checks failed. Maybe true have lowercase t?

**Comment by Lash-L** [comment]
> Checks failed. Maybe true have lowercase t?

I'll give that a try

**Comment by humbertogontijo** [comment]
I saw that it failed. I can only check repository permissions later tomorrow when I get back home. Mobile app does not have repo settings

**Comment by Lash-L** [comment]
Sounds good - no rush! Seemingly just have to allow administrators(like the bot) permission to push directly on the branch?

https://github.com/semantic-release/github/issues/175#issuecomment-527224825

Yeah I find the github mobile app is frequently missing important functionality.

**Pull request merged**
