### PR TITLE
fix: remove depreciated commands

### PR DESCRIPTION
**Pull request by Lash-L**

### CODE REVIEW

**Comment by Lash-L** [comment]
@humbertogontijo not sure if this will actually fix it, but I bumped semantic release to its newest version and it seems to fail. Either this needs to be merged + some changes (maybe) or the pr should be reverted

**Comment by humbertogontijo** [comment]
Removing the pypi token will prevent it from releasing new versions, no? What extra changes are needed? Can't those be in this same PR?

**Comment by Lash-L** [comment]
I think they need a different key now. I’m away from a computer for a week, but I can look once I’m back

I haven’t been able to dove into the docs.

**Comment by Lash-L** [comment]
Perhaps it just needs to be reverted for now

**Pull request closed without merging**
