### PR TITLE
fix: semantic release

### PR DESCRIPTION
**Pull request by Lash-L**
Tested locally and this should work

### CODE REVIEW

**Review by humbertogontijo — APPROVED** [review]

**Comment by Lash-L** [comment]
I'm not sure why when it succeded for one of your last runs, it ended up not actually releasing, stating there was no change.

**Comment by humbertogontijo** [comment]
I added a commit message with latest version and that got fixed. The issue now is construct lib failing build

**Comment by Lash-L** [comment]
It doesn't look like it actually did - no release was actually made. Semantic release passed, but it thought there were no changes so it did not push anything to mypy or github

**Comment by humbertogontijo** [comment]
Check the previous action. That's the one that failed

**Comment by humbertogontijo** [comment]
image

**Comment by Lash-L** [comment]
Yeha I'm talking about the release commit that did succeed when you removed python 3.10
image

**Comment by humbertogontijo** [comment]
I don't want to spend time trying to solve this problem. I just removed python 10 tests from ci
Using only python 11 should be fine

**Pull request merged**
