### PR TITLE
fix: bug with dock commands

### PR DESCRIPTION
**Pull request by Lash-L**
Added test and fix bugs with the docking commands.

### CODE REVIEW

**Comment by humbertogontijo** [comment]
What is the return of commands RoborockCommand.GET_WASH_TOWEL_MODE and RoborockCommand.GET_DUST_COLLECTION_MOD ?

**Comment by Lash-L** [comment]
A single object dict. 

{"mode": 0} or {"wash_mode": 0} Wasn't sure if it was worth creating a container for it

**Comment by humbertogontijo** [comment]
I think we should, cuz dust_collection and washing_mode variables could be None

**Comment by Lash-L** [comment]
Okay sounds  good - I can make that change in a bit. Let me see if the user has any more bugs or feedback and I'll group it.

**Pull request merged**
