### PR TITLE
fix: bump semantic release

### PR DESCRIPTION
**Pull request by Lash-L**
I have no idea if this will work tbh.

But we are so behind on the semantic release versioning it isn't working with the newer python versioning required for the map parser.

I took this config directly from their migration guide.

### CODE REVIEW

**Comment by humbertogontijo** [comment]
I have limited knowledge on GitHub actions and semantic release lib. But we can try it out

**Review by humbertogontijo — DISMISSED** [review]

**Comment by Lash-L** [comment]
Can you give me a invite to the pypi repo again - I didn't accept it in time I guess?

I believe we may have to specify a trusted publisher of this github action https://docs.pypi.org/trusted-publishers/

**Comment by humbertogontijo** [comment]
Invite sent

**Comment by Lash-L** [comment]
@humbertogontijo I should be able to test it now that's its setup just need a approval to be able to merge

**Review by humbertogontijo — APPROVED** [review]

**Pull request merged**
