### PR TITLE
chore: add pyupgrade to ruff

### PR DESCRIPTION
**Pull request by Lash-L**
pyupgrade changes all of our optionals to be | None and a few other changes

### CODE REVIEW

**Comment by humbertogontijo** [comment]
Oh, is this the new preferred approach? I mean, it makes more sense, but I always had complains from mypy that made me go this way haha

**Comment by Lash-L** [comment]
Yeah this is the preferred approach now, but mypy probably contained before we upgraded our python version as this wasn't supported in 3.8

**Comment by humbertogontijo** [comment]
Oh, got it. Thank you

**Review by humbertogontijo — APPROVED** [review]
Looks good

**Pull request merged**
