### PR TITLE
feat: moving clean area to api

### PR DESCRIPTION
**Pull request by Lash-L**
Core doesn't like calculations being done in core, so I moved the division to the api.

### CODE REVIEW

**Comment by humbertogontijo** [comment]
Can you fix mypy for this PR?

**Comment by Lash-L** [comment]
Yes will do in the morning

**Comment by humbertogontijo** [comment]
I dont think we should change the existing field types to Optional[float]

**Comment by Lash-L** [comment]
That was left behind from before I added the new attributes. nice catch, thanks

**Pull request merged**
