### PR TITLE
chore: Update documentation for reset_consumable

### PR DESCRIPTION
**Pull request by Ongion**
This change adds documentation for the API function `reset_consumable`.

It adds information about the format of parameters for the function.

### CODE REVIEW

**Review by humbertogontijo — APPROVED** [review]
Looks good

**Review by humbertogontijo — COMMENTED** [review]
Actually you might need to change commit message

**Comment by Ongion** [comment]
Oh, I guess the commit message needs to have "chore:" as a prefix? Gimme a sec and I'll amend that...

**Comment by Ongion** [comment]
Alright, commit message amended

**Pull request merged**
