### PR TITLE
chore: added code from decompiled react and refactoring web api

### PR DESCRIPTION
**Pull request by Lash-L**
So A01 has been decoded, but there's going to end up being some changes that need to be made. So I did some refactoring so that when the changes are made, less code will be impacted.

If you're curious here is how it is decrypted:
```
		A01_HASH = 726f626f726f636b2d67a6d6da
        iv = md5hex(format(context.random, "08x") + A01_HASH)[8:24]
        decipher = AES.new(bytes("ELSYN0wTI4AUm7C4", "utf-8"), AES.MODE_CBC, bytes(iv, "utf-8"))
        f = decipher.decrypt(obj)
        response = json.loads(f)
        new_dps = {}
        for key in response["dps"]:
            new_dps[RoborockDyadDataProtocol(int(key))] = response["dps"][key]
        response["dps"] = new_dps

```

Results in:

```
Container: 
    version = b'A01' (total 3)
    seq = 11017
    random = 11017
    timestamp = 1703950501
    protocol = 102
{'t': 1703950501, 'dps': {<RoborockDyadDataProtocol.START: 200>: 1, <RoborockDyadDataProtocol.STATUS: 201>: 10, <RoborockDyadDataProtocol.SELF_CLEAN_MODE: 202>: 0, <RoborockDyadDataProtocol.SELF_CLEAN_LEVEL: 203>: 1, <RoborockDyadDataProtocol.WARM_LEVEL: 204>: 1, <RoborockDyadDataProtocol.CLEAN_MODE: 205>: 1, <RoborockDyadDataProtocol.SUCTION: 206>: 3, <RoborockDyadDataProtocol.WATER_LEVEL: 207>: 4, <RoborockDyadDataProtocol.BRUSH_SPEED: 208>: 1, <RoborockDyadDataProtocol.POWER: 209>: 95, <RoborockDyadDataProtocol.COUNTDOWN_TIME: 210>: 0, <RoborockDyadDataProtocol.AUTO_SELF_CLEAN_SET: 212>: 1, <RoborockDyadDataProtocol.AUTO_DRY: 213>: 1, <RoborockDyadDataProtocol.MESH_LEF: 214>: 254, <RoborockDyadDataProtocol.BRUSH_LEFT: 215>: 254, <RoborockDyadDataProtocol.ERROR: 216>: 0, <RoborockDyadDataProtocol.VOLUME_SET: 221>: 100, <RoborockDyadDataProtocol.STAND_LOCK_AUTO_RUN: 222>: 0, <RoborockDyadDataProtocol.AUTO_SELF_CLEAN_SET_MODE: 223>: 1, <RoborockDyadDataProtocol.AUTO_DRY_MODE: 224>: 1, <RoborockDyadDataProtocol.SILENT_DRY_DURATION: 225>: 240, <RoborockDyadDataProtocol.SILENT_MODE: 226>: 0, <RoborockDyadDataProtocol.SILENT_MODE_START_TIME: 227>: 1320, <RoborockDyadDataProtocol.SILENT_MODE_END_TIME: 228>: 360}}

```

More PRS will follow, but trying to not make it too big. Will be adding these as 'chores' until we are ready to release a new version and then it will be released as major, since it will change a lot

### CODE REVIEW

**Comment by humbertogontijo** [comment]
Uff, that looks a lot different. Good job figuring A01 out

**Comment by humbertogontijo** [comment]
I also liked you removing web api stuff to another file

**Review by humbertogontijo — APPROVED** [review]
Good job. Looks good

**Comment by Lash-L** [comment]
> Uff, that looks a lot different. Good job figuring A01 out

It was a group effort. In a discord chat with rovo (the guy who originally got the salt) and copystring (a guy working on a iobroker roborock integration). If you want me to add you to it, just lmk.

**Pull request merged**
