### PR TITLE
Moved map parser to package for future cleanup

### PR DESCRIPTION
**Pull request by Lash-L**
In the future I'll take the time to fully convert the component to use this part of the package instead, but for now I am moving it here so that it is possible to do in the future

### CODE REVIEW

**Comment by humbertogontijo** [comment]
To be honest we should use a library or include the map with @PiotrMachowski integration. No point on keeping a copy of his code

**Comment by Lash-L** [comment]
Agreed that would be best case. I don't believe he has a pypi package for his map parser though - and we'll need one when this part of the codebase eventually makes it to core (who knows how long that will be). I could potentially make one if he would like.

**Comment by PiotrMachowski** [comment]
I think I could make a package out of it, but it would require a significant bit of work. Before that I would prefer to use a different image rendering library - pillow seems to be a little bit slow (maybe my code is not optimized enough though). 

Recently I have been working more on the Map Card instead of Map Extractor so it has some pending maintenance.

**Comment by Lash-L** [comment]
@PiotrMachowski awesome - let me know if I can help in anyway

**Comment by PiotrMachowski** [comment]
@Lash-L can you make a feature request in Map Extractor to keep a record of this discussion in my repo as well?

**Comment by Lash-L** [comment]
> @Lash-L can you make a feature request in Map Extractor to keep a record of this discussion in my repo as well?

Done.

**Pull request closed without merging**
